name:                haskell-trace-types
version:             0.1.0.0
github:              "probcomp/haskell-trace-types"
license:             MIT
author:              "Alex Lew"
maintainer:          "alexlew@mit.edu"
copyright:           "2019-2025 Alex Lew"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/probcomp/haskell-trace-types#readme>

dependencies:
- base >= 4.7 && < 5
- unconstrained
- text
- hashable
- vector-sized
- unordered-containers
- constraints
- row-types
- deepseq
- random
- containers
- monad-bayes
- log-domain
- finite-typelits
- data-default
- statistics

library:
  source-dirs: src

executables:
  trace-types-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-trace-types

